### PR TITLE
Add referer header when autodetecting SmartHub 2

### PR DESCRIPTION
**Pull request by typhoon2099**
My previous PR missed a request during autodetecting which SmartHub is being talked to. The current workaround in Home Assistant is to specify the version, but this PR will correct the issue so users don't need to do this.

Obviously a new version will need to be published to downstream it to Home Assistant.

### CODE REVIEW

**Comment by jxwolstenholme** [comment]
I can see that there's another issue with apostrophes somewhere in there. Do you want to submit a PR for that as well and I can then bundle up a new version to PyPi?

**Comment by jxwolstenholme** [comment]
Actually - going to try and add you as a "collaborator" on github if you're willing to take it over. Seen your other post offering and yes, would love you to as I no longer have any use for this repo or the ability to test it! If you can send me your PyPi username as well it would be great to get you as the admin over there too.

**Comment by typhoon2099** [comment]
Oh great, thanks! My PyPi username is `typhoon_2099`.

**Comment by jxwolstenholme** [comment]
> Oh great, thanks! My PyPi username is `typhoon_2099`.

PyPi not happy with your username as you need to verify your email address

"User 'typhoon_2099' does not have a verified primary email address and cannot be added as a Maintainer for project"

Will you verify and I can then get you added

Thanks for taking it on!

**Comment by typhoon2099** [comment]
I've verified now, I didn't expect such a quick response!

**Pull request merged**
