### PR TITLE
Add support for EE smarthub

### PR DESCRIPTION
**Pull request by splinter98**
EE (which is owned by BT) also provide smart hubs and these are essentially the same hardware as BT Smart hubs, however the urls are a little different. This adds support for these hubs.

I also took the liberty to simplify some of the try..except logic to reduce the amount of indentation required.

### CODE REVIEW

**Comment by jxwolstenholme** [comment]
Thanks @splinter98 - looks good.

Happy to merge if you update the readme to reflect the new functionality!

**Comment by splinter98** [comment]
@jxwolstenholme I've updated the readme, I have also added a check so that `include_connections` code path doesn't get executed as cgi_owl.js doesn't exist and there doesn't seem to be any alternative, partly because EE don't have the WiFi disks supported like BT.

**Comment by jxwolstenholme** [comment]
Brilliant - thank you.

What's your stance on the dtype of the smarthub_model argument?

Do you reckon it would be better to just convert everything over to a string now?

**Comment by splinter98** [comment]
> Brilliant - thank you.
> 
> What's your stance on the dtype of the smarthub_model argument?
> 
> Do you reckon it would be better to just convert everything over to a string now?

I somehow missed this question, so apologies for the delay.

Regarding  the dtype of the smarthub_model argument I think a single type is definitely better than the current mix. (I didn't want to make too many changes as part of this pull request but the current mix isn't ideal).

I think transferring to strings is definitely better, and likely to be eventually required depending on how many variants/revisions of the smarthub that will need supporting.

I don't think we necessarily need to go to dedicated objects or using an enum but I'm not against them either.

**Pull request merged**
