### PR TITLE
Added support for additional data from Smart Hub 2 devices.

### PR DESCRIPTION
**Pull request by goul**
Namely :

'ConnectionType', 'ParentPhysAddress', 'ParentName'

Connection Type is Ether|5G|2.4G (G->Ghz)

ParentName is the name of the device the client is connecting through, i.e. the name of the disk or the core router itself.
ParentPhyAddress is the Mac Address of the  Parent.

Disks, the core router and inactive clients will have these additional fields set to 'Unknown'.

### CODE REVIEW

**Comment by goul** [comment]
Please excuse my lack of python experience. I've been trying to get the tests etc all running using the tox.ini setup in the project.

For me, the tests don't execute via tox unless the test directory/fixtures etc are a sub-directory of the btsmarthub_devicelist directory. Am I missing something on why original tests dir is in the root directory?

**Comment by jxwolstenholme** [comment]
First of all, huge thanks for the work.

Regarding the tests, you're correct that they will not run at the minute. I didn't set up that tox file and haven't actually used it but in the commands, the btsmarthub_devicelist term needs to be removed so that `commands = pytest --verbose {posargs}`. I can change it but might be cleaner if you do and then everything is fixed in one neat PR. 

After that, due to the way tox creates the virtual environment on its test runs, I think that your  imports of the .js files will need to be prepended with tests/ e.g.
`with open('tests/fixtures/smarthub2/cgi_owl.js', 'r') as file:`

And you will need to add responses to the deps

Having run it, I can see that one of the original tests fails anyway so don't worry about that one. I'll fix it at a later date.

One thing that might be useful to add to your PR is the ability to optionally request the additional data that you have provided. Perhaps set up a flag in `get_devicelist()` for say **include_connections**   ?
Thinking about Home Assistant - where this module is mostly used - it would probably be best to give the option to limit requests to 1 (cgi_basicMyDevice.js) rather than making 2 requests every time with cgi_owl.js to limit the load on the router as it is polled every few seconds I think.

**Comment by goul** [comment]
Sounds good - I'll have a tweak of the tox setup, get_gevicelist() and the double read tonight.

**Review by jxwolstenholme — APPROVED** [review]
All looks sensible to me - will merge

**Pull request merged**
